### ISSUE TITLE
Message Type

### ISSUE THREAD

**Issue by eaba** [mrtaikandi/Telebot#1]
Thanks for the Library but it is missing the ability to detect what type of Message we are dealing with.
I am trying to find a way to tell if the message is a Text or File.

Is there already a way to do this? Please show me.

**Comment by eaba** [comment]
Please can the DownloadFile method return byte array?
This is useful when I dont want to save to hard disk

**Comment by mrtaikandi** [comment]
Thanks for using my library :smile: 

If you look at the Bot API documentation the Message type doesn't have any types. To figure out what type of message the received message is you have to check its properties. For example, if the received message contains an audio file the Message.Audio property is not null.

As for the DownloadFile method, it is a really good idea. I will add it as soon as possible. 
Thanks for the suggestion. :+1:

**Comment by mrtaikandi** [comment]
Please update your nuget packages to 2.0.2. The requested overload of DownloadFile has been added.

**Comment by eaba** [comment]
Thanks for adding the Download overload!
On checking the type of message, maybe we could borrow an idea from https://github.com/MrRoundRobin/telegram.bot

**Comment by mrtaikandi** [comment]
Technically it does what I said before. Even with the MessageType you have to check either with an if statement or switch to do whatever necessary. That was why I didn't add that before. But If you think it would be beneficial to have one, I will add a Type property to the Message class. 

Again, thanks for the suggestion :blush:

**Comment by mrtaikandi** [comment]
I've added [another issue](https://github.com/mrtaikandi/Telebot/issues/2) regarding this. If you have any other suggestion, I appriciate if you open new issues for each one to have better collaboration.

Thanks

**Comment by eaba** [comment]
Thank you!
