### ISSUE TITLE
 .NET Core v1.1 compatibility

### ISSUE THREAD

**Issue by Dolfik1** [mrtaikandi/Telebot#12]
The library not compatible with .Net Core 1.1.

Errors in
    Package Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.AspNet.WebApi.Client 5.2.3 supports:
      - net45 (.NETFramework,Version=v4.5)
      - portable-net45+netcore45+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=wp8+netcore45+net45+wp81+wpa81)
    One or more packages are incompatible with .NETCoreApp,Version=v1.1.

**Comment by mrtaikandi** [comment]
Thanks for reporting this. 

I have updated the Nuget package to support NetStandard 1.3.
