### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by Warlockx** [mrtaikandi/Telebot#3]
Hi, Ive been getting those error's but i really dont know why. Ive been using the same code for a while now and never had problems but now even if i only try to
`await tbot.SendMessageAsync(message.Chat.Id, "test test");` i get this error 
'400': [Error]: Bad Request: Object expected as reply markup.

**Comment by mrtaikandi** [comment]
Hi warlockx, 
I took a quick look at your problem and it seems that the Telegram changed the way it processes the sent messages and now it is required to send a reply markup. 

I have to check if I'm correct before apply any changes but for now you can send a type of reply markup with your messages. For example: 

`await Telebot.SendMessageAsync(message.Chat.Id, "Hmmmm", replyMarkup: new ReplyKeyboardHide());`

**Comment by Warlockx** [comment]
thanks for the quick reply, i thought they had blocked my bot or something... ill add this workaround in my code thanks.

**Comment by mrtaikandi** [comment]
The problem has been fixed with the @vmtco help. You can now use the API like the way you used before.
