### ISSUE TITLE
Most long properties are integer in the API

### ISSUE THREAD

**Issue by rgbweb** [mrtaikandi/Telebot#6]
Hi,

Thanks for creating the library and updating it that fast after the latest API change!

But, is there a special reason why properties like `Chat.Id`, `Message.Id` and `Update.Id` are of type long? The Telegram documentation uses Integer for all three properties:
https://core.telegram.org/bots/api#update
https://core.telegram.org/bots/api#message
https://core.telegram.org/bots/api#chat

It should not be a problem to use long internally because the values are generated by the Telegram servers. But there is a type mismatch at least in the `messageId` parameters in the edit message methods:
https://github.com/mrtaikandi/Telebot/blob/master/src/Telebot/Telebot.message-edit.cs#L35

```
        public Task<Message> EditMessageCaptionAsync(long chatId, int messageId, [NotNull] string caption, InlineKeyboardMarkup replyMarkup = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            Contracts.EnsurePositiveNumber(chatId, nameof(chatId));
            return this.EditMessageCaptionAsync(chatId.ToString(), messageId, caption, replyMarkup, cancellationToken);
        }
```

The `chatId` is of type long and the `messageId` of type int. The API documentation again has both in Integer.

Cheers

**Comment by mrtaikandi** [comment]
Hi,

The integer in the Telegram documentation indicates that the type is numeral and not the type of int in the .NET. In .NET int is equal to Int32 which is 32bit long but the integer in the Telegram API is 64bit long which is equal to long in .NET world. 

About the EditMessageCaptionAsync method you are correct. This is a bug and I will fix it as soon as possible. 

Thank you for using my library and I appreciate if you report any further bugs you encounter.

**Comment by mrtaikandi** [comment]
I've fixed the issue you mentioned and updated the nuget package. 
Thanks again for reporting this.
