### ISSUE TITLE
Error in CheckInlineQuery Async

### ISSUE THREAD

**Issue by elia07** [mrtaikandi/Telebot#9]
Hi Dear Mr Taikandi and Tanx for your awesome project.

propery of MessageContent in InlineQueryResultArticle class needs to be initialized and you missed in your example and this cause an error 

please just change 

var articleResult = new InlineQueryResultArticle
            {
                Id = Guid.NewGuid().ToString("N"),
                Title = "This is a title",
                Url = "https://core.telegram.org/bots/api#inlinequeryresultarticle"

```
        };
```

to 

var articleResult = new InlineQueryResultArticle
            {
                Id = Guid.NewGuid().ToString("N"),
                Title = "This is a title",
                Url = "https://core.telegram.org/bots/api#inlinequeryresultarticle",
                MessageContent = new InputTextMessageContent { MessageText="this is"}

```
        };
```

and every thing works awesome , tanx again for your project

**Comment by mrtaikandi** [comment]
Thanks. I will update the sample code.
